/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var basic_types_pb = require('./basic_types_pb.js');
goog.exportSymbol('proto.proto.CryptoDeleteAllowanceTransactionBody', null, global);
goog.exportSymbol('proto.proto.CryptoRemoveAllowance', null, global);
goog.exportSymbol('proto.proto.NftRemoveAllowance', null, global);
goog.exportSymbol('proto.proto.TokenRemoveAllowance', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.CryptoDeleteAllowanceTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.CryptoDeleteAllowanceTransactionBody.repeatedFields_, null);
};
goog.inherits(proto.proto.CryptoDeleteAllowanceTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.CryptoDeleteAllowanceTransactionBody.displayName = 'proto.proto.CryptoDeleteAllowanceTransactionBody';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.CryptoDeleteAllowanceTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.CryptoDeleteAllowanceTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    cryptoallowancesList: jspb.Message.toObjectList(msg.getCryptoallowancesList(),
    proto.proto.CryptoRemoveAllowance.toObject, includeInstance),
    nftallowancesList: jspb.Message.toObjectList(msg.getNftallowancesList(),
    proto.proto.NftRemoveAllowance.toObject, includeInstance),
    tokenallowancesList: jspb.Message.toObjectList(msg.getTokenallowancesList(),
    proto.proto.TokenRemoveAllowance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.CryptoDeleteAllowanceTransactionBody}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.CryptoDeleteAllowanceTransactionBody;
  return proto.proto.CryptoDeleteAllowanceTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.CryptoDeleteAllowanceTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.CryptoDeleteAllowanceTransactionBody}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.CryptoRemoveAllowance;
      reader.readMessage(value,proto.proto.CryptoRemoveAllowance.deserializeBinaryFromReader);
      msg.addCryptoallowances(value);
      break;
    case 2:
      var value = new proto.proto.NftRemoveAllowance;
      reader.readMessage(value,proto.proto.NftRemoveAllowance.deserializeBinaryFromReader);
      msg.addNftallowances(value);
      break;
    case 3:
      var value = new proto.proto.TokenRemoveAllowance;
      reader.readMessage(value,proto.proto.TokenRemoveAllowance.deserializeBinaryFromReader);
      msg.addTokenallowances(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.CryptoDeleteAllowanceTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.CryptoDeleteAllowanceTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCryptoallowancesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.proto.CryptoRemoveAllowance.serializeBinaryToWriter
    );
  }
  f = message.getNftallowancesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.proto.NftRemoveAllowance.serializeBinaryToWriter
    );
  }
  f = message.getTokenallowancesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.proto.TokenRemoveAllowance.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CryptoRemoveAllowance cryptoAllowances = 1;
 * @return {!Array.<!proto.proto.CryptoRemoveAllowance>}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.getCryptoallowancesList = function() {
  return /** @type{!Array.<!proto.proto.CryptoRemoveAllowance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.CryptoRemoveAllowance, 1));
};


/** @param {!Array.<!proto.proto.CryptoRemoveAllowance>} value */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.setCryptoallowancesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.proto.CryptoRemoveAllowance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.CryptoRemoveAllowance}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.addCryptoallowances = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.proto.CryptoRemoveAllowance, opt_index);
};


proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.clearCryptoallowancesList = function() {
  this.setCryptoallowancesList([]);
};


/**
 * repeated NftRemoveAllowance nftAllowances = 2;
 * @return {!Array.<!proto.proto.NftRemoveAllowance>}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.getNftallowancesList = function() {
  return /** @type{!Array.<!proto.proto.NftRemoveAllowance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.NftRemoveAllowance, 2));
};


/** @param {!Array.<!proto.proto.NftRemoveAllowance>} value */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.setNftallowancesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.NftRemoveAllowance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.NftRemoveAllowance}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.addNftallowances = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.NftRemoveAllowance, opt_index);
};


proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.clearNftallowancesList = function() {
  this.setNftallowancesList([]);
};


/**
 * repeated TokenRemoveAllowance tokenAllowances = 3;
 * @return {!Array.<!proto.proto.TokenRemoveAllowance>}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.getTokenallowancesList = function() {
  return /** @type{!Array.<!proto.proto.TokenRemoveAllowance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.TokenRemoveAllowance, 3));
};


/** @param {!Array.<!proto.proto.TokenRemoveAllowance>} value */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.setTokenallowancesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.TokenRemoveAllowance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.TokenRemoveAllowance}
 */
proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.addTokenallowances = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.TokenRemoveAllowance, opt_index);
};


proto.proto.CryptoDeleteAllowanceTransactionBody.prototype.clearTokenallowancesList = function() {
  this.setTokenallowancesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.CryptoRemoveAllowance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.CryptoRemoveAllowance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.CryptoRemoveAllowance.displayName = 'proto.proto.CryptoRemoveAllowance';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.CryptoRemoveAllowance.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.CryptoRemoveAllowance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.CryptoRemoveAllowance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CryptoRemoveAllowance.toObject = function(includeInstance, msg) {
  var f, obj = {
    owner: (f = msg.getOwner()) && basic_types_pb.AccountID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.CryptoRemoveAllowance}
 */
proto.proto.CryptoRemoveAllowance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.CryptoRemoveAllowance;
  return proto.proto.CryptoRemoveAllowance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.CryptoRemoveAllowance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.CryptoRemoveAllowance}
 */
proto.proto.CryptoRemoveAllowance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.AccountID;
      reader.readMessage(value,basic_types_pb.AccountID.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.CryptoRemoveAllowance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.CryptoRemoveAllowance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.CryptoRemoveAllowance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CryptoRemoveAllowance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.AccountID.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccountID owner = 1;
 * @return {?proto.proto.AccountID}
 */
proto.proto.CryptoRemoveAllowance.prototype.getOwner = function() {
  return /** @type{?proto.proto.AccountID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.AccountID, 1));
};


/** @param {?proto.proto.AccountID|undefined} value */
proto.proto.CryptoRemoveAllowance.prototype.setOwner = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.CryptoRemoveAllowance.prototype.clearOwner = function() {
  this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.CryptoRemoveAllowance.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.NftRemoveAllowance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.NftRemoveAllowance.repeatedFields_, null);
};
goog.inherits(proto.proto.NftRemoveAllowance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.NftRemoveAllowance.displayName = 'proto.proto.NftRemoveAllowance';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.NftRemoveAllowance.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.NftRemoveAllowance.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.NftRemoveAllowance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.NftRemoveAllowance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.NftRemoveAllowance.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenId: (f = msg.getTokenId()) && basic_types_pb.TokenID.toObject(includeInstance, f),
    owner: (f = msg.getOwner()) && basic_types_pb.AccountID.toObject(includeInstance, f),
    serialNumbersList: jspb.Message.getRepeatedField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.NftRemoveAllowance}
 */
proto.proto.NftRemoveAllowance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.NftRemoveAllowance;
  return proto.proto.NftRemoveAllowance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.NftRemoveAllowance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.NftRemoveAllowance}
 */
proto.proto.NftRemoveAllowance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.TokenID;
      reader.readMessage(value,basic_types_pb.TokenID.deserializeBinaryFromReader);
      msg.setTokenId(value);
      break;
    case 2:
      var value = new basic_types_pb.AccountID;
      reader.readMessage(value,basic_types_pb.AccountID.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 3:
      var value = /** @type {!Array.<number>} */ (reader.readPackedInt64());
      msg.setSerialNumbersList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.NftRemoveAllowance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.NftRemoveAllowance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.NftRemoveAllowance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.NftRemoveAllowance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.TokenID.serializeBinaryToWriter
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      basic_types_pb.AccountID.serializeBinaryToWriter
    );
  }
  f = message.getSerialNumbersList();
  if (f.length > 0) {
    writer.writePackedInt64(
      3,
      f
    );
  }
};


/**
 * optional TokenID token_id = 1;
 * @return {?proto.proto.TokenID}
 */
proto.proto.NftRemoveAllowance.prototype.getTokenId = function() {
  return /** @type{?proto.proto.TokenID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.TokenID, 1));
};


/** @param {?proto.proto.TokenID|undefined} value */
proto.proto.NftRemoveAllowance.prototype.setTokenId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.NftRemoveAllowance.prototype.clearTokenId = function() {
  this.setTokenId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.NftRemoveAllowance.prototype.hasTokenId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AccountID owner = 2;
 * @return {?proto.proto.AccountID}
 */
proto.proto.NftRemoveAllowance.prototype.getOwner = function() {
  return /** @type{?proto.proto.AccountID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.AccountID, 2));
};


/** @param {?proto.proto.AccountID|undefined} value */
proto.proto.NftRemoveAllowance.prototype.setOwner = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.proto.NftRemoveAllowance.prototype.clearOwner = function() {
  this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.NftRemoveAllowance.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated int64 serial_numbers = 3;
 * @return {!Array.<number>}
 */
proto.proto.NftRemoveAllowance.prototype.getSerialNumbersList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array.<number>} value */
proto.proto.NftRemoveAllowance.prototype.setSerialNumbersList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.proto.NftRemoveAllowance.prototype.addSerialNumbers = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.proto.NftRemoveAllowance.prototype.clearSerialNumbersList = function() {
  this.setSerialNumbersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.TokenRemoveAllowance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.TokenRemoveAllowance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.TokenRemoveAllowance.displayName = 'proto.proto.TokenRemoveAllowance';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.TokenRemoveAllowance.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.TokenRemoveAllowance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.TokenRemoveAllowance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TokenRemoveAllowance.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenId: (f = msg.getTokenId()) && basic_types_pb.TokenID.toObject(includeInstance, f),
    owner: (f = msg.getOwner()) && basic_types_pb.AccountID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.TokenRemoveAllowance}
 */
proto.proto.TokenRemoveAllowance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.TokenRemoveAllowance;
  return proto.proto.TokenRemoveAllowance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.TokenRemoveAllowance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.TokenRemoveAllowance}
 */
proto.proto.TokenRemoveAllowance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.TokenID;
      reader.readMessage(value,basic_types_pb.TokenID.deserializeBinaryFromReader);
      msg.setTokenId(value);
      break;
    case 2:
      var value = new basic_types_pb.AccountID;
      reader.readMessage(value,basic_types_pb.AccountID.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.TokenRemoveAllowance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.TokenRemoveAllowance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.TokenRemoveAllowance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TokenRemoveAllowance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.TokenID.serializeBinaryToWriter
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      basic_types_pb.AccountID.serializeBinaryToWriter
    );
  }
};


/**
 * optional TokenID token_id = 1;
 * @return {?proto.proto.TokenID}
 */
proto.proto.TokenRemoveAllowance.prototype.getTokenId = function() {
  return /** @type{?proto.proto.TokenID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.TokenID, 1));
};


/** @param {?proto.proto.TokenID|undefined} value */
proto.proto.TokenRemoveAllowance.prototype.setTokenId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.TokenRemoveAllowance.prototype.clearTokenId = function() {
  this.setTokenId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TokenRemoveAllowance.prototype.hasTokenId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AccountID owner = 2;
 * @return {?proto.proto.AccountID}
 */
proto.proto.TokenRemoveAllowance.prototype.getOwner = function() {
  return /** @type{?proto.proto.AccountID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.AccountID, 2));
};


/** @param {?proto.proto.AccountID|undefined} value */
proto.proto.TokenRemoveAllowance.prototype.setOwner = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.proto.TokenRemoveAllowance.prototype.clearOwner = function() {
  this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TokenRemoveAllowance.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.proto);
