/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var system_delete_pb = require('./system_delete_pb.js');
var system_undelete_pb = require('./system_undelete_pb.js');
var freeze_pb = require('./freeze_pb.js');
var contract_call_pb = require('./contract_call_pb.js');
var contract_create_pb = require('./contract_create_pb.js');
var contract_update_pb = require('./contract_update_pb.js');
var crypto_create_pb = require('./crypto_create_pb.js');
var crypto_delete_pb = require('./crypto_delete_pb.js');
var crypto_transfer_pb = require('./crypto_transfer_pb.js');
var crypto_update_pb = require('./crypto_update_pb.js');
var crypto_approve_allowance_pb = require('./crypto_approve_allowance_pb.js');
var crypto_adjust_allowance_pb = require('./crypto_adjust_allowance_pb.js');
var crypto_delete_allowance_pb = require('./crypto_delete_allowance_pb.js');
var file_append_pb = require('./file_append_pb.js');
var file_create_pb = require('./file_create_pb.js');
var file_delete_pb = require('./file_delete_pb.js');
var file_update_pb = require('./file_update_pb.js');
var contract_delete_pb = require('./contract_delete_pb.js');
var consensus_create_topic_pb = require('./consensus_create_topic_pb.js');
var consensus_update_topic_pb = require('./consensus_update_topic_pb.js');
var consensus_delete_topic_pb = require('./consensus_delete_topic_pb.js');
var consensus_submit_message_pb = require('./consensus_submit_message_pb.js');
var token_create_pb = require('./token_create_pb.js');
var token_freeze_account_pb = require('./token_freeze_account_pb.js');
var token_unfreeze_account_pb = require('./token_unfreeze_account_pb.js');
var token_grant_kyc_pb = require('./token_grant_kyc_pb.js');
var token_revoke_kyc_pb = require('./token_revoke_kyc_pb.js');
var token_delete_pb = require('./token_delete_pb.js');
var token_update_pb = require('./token_update_pb.js');
var token_mint_pb = require('./token_mint_pb.js');
var token_burn_pb = require('./token_burn_pb.js');
var token_wipe_account_pb = require('./token_wipe_account_pb.js');
var token_associate_pb = require('./token_associate_pb.js');
var token_dissociate_pb = require('./token_dissociate_pb.js');
var token_fee_schedule_update_pb = require('./token_fee_schedule_update_pb.js');
var token_pause_pb = require('./token_pause_pb.js');
var token_unpause_pb = require('./token_unpause_pb.js');
var schedule_delete_pb = require('./schedule_delete_pb.js');
goog.exportSymbol('proto.proto.SchedulableTransactionBody', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.SchedulableTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.proto.SchedulableTransactionBody.oneofGroups_);
};
goog.inherits(proto.proto.SchedulableTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.SchedulableTransactionBody.displayName = 'proto.proto.SchedulableTransactionBody';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.proto.SchedulableTransactionBody.oneofGroups_ = [[3,4,5,6,37,38,40,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,39,35,36,34]];

/**
 * @enum {number}
 */
proto.proto.SchedulableTransactionBody.DataCase = {
  DATA_NOT_SET: 0,
  CONTRACTCALL: 3,
  CONTRACTCREATEINSTANCE: 4,
  CONTRACTUPDATEINSTANCE: 5,
  CONTRACTDELETEINSTANCE: 6,
  CRYPTOADJUSTALLOWANCE: 37,
  CRYPTOAPPROVEALLOWANCE: 38,
  CRYPTODELETEALLOWANCE: 40,
  CRYPTOCREATEACCOUNT: 7,
  CRYPTODELETE: 8,
  CRYPTOTRANSFER: 9,
  CRYPTOUPDATEACCOUNT: 10,
  FILEAPPEND: 11,
  FILECREATE: 12,
  FILEDELETE: 13,
  FILEUPDATE: 14,
  SYSTEMDELETE: 15,
  SYSTEMUNDELETE: 16,
  FREEZE: 17,
  CONSENSUSCREATETOPIC: 18,
  CONSENSUSUPDATETOPIC: 19,
  CONSENSUSDELETETOPIC: 20,
  CONSENSUSSUBMITMESSAGE: 21,
  TOKENCREATION: 22,
  TOKENFREEZE: 23,
  TOKENUNFREEZE: 24,
  TOKENGRANTKYC: 25,
  TOKENREVOKEKYC: 26,
  TOKENDELETION: 27,
  TOKENUPDATE: 28,
  TOKENMINT: 29,
  TOKENBURN: 30,
  TOKENWIPE: 31,
  TOKENASSOCIATE: 32,
  TOKENDISSOCIATE: 33,
  TOKEN_FEE_SCHEDULE_UPDATE: 39,
  TOKEN_PAUSE: 35,
  TOKEN_UNPAUSE: 36,
  SCHEDULEDELETE: 34
};

/**
 * @return {proto.proto.SchedulableTransactionBody.DataCase}
 */
proto.proto.SchedulableTransactionBody.prototype.getDataCase = function() {
  return /** @type {proto.proto.SchedulableTransactionBody.DataCase} */(jspb.Message.computeOneofCase(this, proto.proto.SchedulableTransactionBody.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.SchedulableTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.SchedulableTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.SchedulableTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SchedulableTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionfee: jspb.Message.getFieldWithDefault(msg, 1, 0),
    memo: jspb.Message.getFieldWithDefault(msg, 2, ""),
    contractcall: (f = msg.getContractcall()) && contract_call_pb.ContractCallTransactionBody.toObject(includeInstance, f),
    contractcreateinstance: (f = msg.getContractcreateinstance()) && contract_create_pb.ContractCreateTransactionBody.toObject(includeInstance, f),
    contractupdateinstance: (f = msg.getContractupdateinstance()) && contract_update_pb.ContractUpdateTransactionBody.toObject(includeInstance, f),
    contractdeleteinstance: (f = msg.getContractdeleteinstance()) && contract_delete_pb.ContractDeleteTransactionBody.toObject(includeInstance, f),
    cryptoadjustallowance: (f = msg.getCryptoadjustallowance()) && crypto_adjust_allowance_pb.CryptoAdjustAllowanceTransactionBody.toObject(includeInstance, f),
    cryptoapproveallowance: (f = msg.getCryptoapproveallowance()) && crypto_approve_allowance_pb.CryptoApproveAllowanceTransactionBody.toObject(includeInstance, f),
    cryptodeleteallowance: (f = msg.getCryptodeleteallowance()) && crypto_delete_allowance_pb.CryptoDeleteAllowanceTransactionBody.toObject(includeInstance, f),
    cryptocreateaccount: (f = msg.getCryptocreateaccount()) && crypto_create_pb.CryptoCreateTransactionBody.toObject(includeInstance, f),
    cryptodelete: (f = msg.getCryptodelete()) && crypto_delete_pb.CryptoDeleteTransactionBody.toObject(includeInstance, f),
    cryptotransfer: (f = msg.getCryptotransfer()) && crypto_transfer_pb.CryptoTransferTransactionBody.toObject(includeInstance, f),
    cryptoupdateaccount: (f = msg.getCryptoupdateaccount()) && crypto_update_pb.CryptoUpdateTransactionBody.toObject(includeInstance, f),
    fileappend: (f = msg.getFileappend()) && file_append_pb.FileAppendTransactionBody.toObject(includeInstance, f),
    filecreate: (f = msg.getFilecreate()) && file_create_pb.FileCreateTransactionBody.toObject(includeInstance, f),
    filedelete: (f = msg.getFiledelete()) && file_delete_pb.FileDeleteTransactionBody.toObject(includeInstance, f),
    fileupdate: (f = msg.getFileupdate()) && file_update_pb.FileUpdateTransactionBody.toObject(includeInstance, f),
    systemdelete: (f = msg.getSystemdelete()) && system_delete_pb.SystemDeleteTransactionBody.toObject(includeInstance, f),
    systemundelete: (f = msg.getSystemundelete()) && system_undelete_pb.SystemUndeleteTransactionBody.toObject(includeInstance, f),
    freeze: (f = msg.getFreeze()) && freeze_pb.FreezeTransactionBody.toObject(includeInstance, f),
    consensuscreatetopic: (f = msg.getConsensuscreatetopic()) && consensus_create_topic_pb.ConsensusCreateTopicTransactionBody.toObject(includeInstance, f),
    consensusupdatetopic: (f = msg.getConsensusupdatetopic()) && consensus_update_topic_pb.ConsensusUpdateTopicTransactionBody.toObject(includeInstance, f),
    consensusdeletetopic: (f = msg.getConsensusdeletetopic()) && consensus_delete_topic_pb.ConsensusDeleteTopicTransactionBody.toObject(includeInstance, f),
    consensussubmitmessage: (f = msg.getConsensussubmitmessage()) && consensus_submit_message_pb.ConsensusSubmitMessageTransactionBody.toObject(includeInstance, f),
    tokencreation: (f = msg.getTokencreation()) && token_create_pb.TokenCreateTransactionBody.toObject(includeInstance, f),
    tokenfreeze: (f = msg.getTokenfreeze()) && token_freeze_account_pb.TokenFreezeAccountTransactionBody.toObject(includeInstance, f),
    tokenunfreeze: (f = msg.getTokenunfreeze()) && token_unfreeze_account_pb.TokenUnfreezeAccountTransactionBody.toObject(includeInstance, f),
    tokengrantkyc: (f = msg.getTokengrantkyc()) && token_grant_kyc_pb.TokenGrantKycTransactionBody.toObject(includeInstance, f),
    tokenrevokekyc: (f = msg.getTokenrevokekyc()) && token_revoke_kyc_pb.TokenRevokeKycTransactionBody.toObject(includeInstance, f),
    tokendeletion: (f = msg.getTokendeletion()) && token_delete_pb.TokenDeleteTransactionBody.toObject(includeInstance, f),
    tokenupdate: (f = msg.getTokenupdate()) && token_update_pb.TokenUpdateTransactionBody.toObject(includeInstance, f),
    tokenmint: (f = msg.getTokenmint()) && token_mint_pb.TokenMintTransactionBody.toObject(includeInstance, f),
    tokenburn: (f = msg.getTokenburn()) && token_burn_pb.TokenBurnTransactionBody.toObject(includeInstance, f),
    tokenwipe: (f = msg.getTokenwipe()) && token_wipe_account_pb.TokenWipeAccountTransactionBody.toObject(includeInstance, f),
    tokenassociate: (f = msg.getTokenassociate()) && token_associate_pb.TokenAssociateTransactionBody.toObject(includeInstance, f),
    tokendissociate: (f = msg.getTokendissociate()) && token_dissociate_pb.TokenDissociateTransactionBody.toObject(includeInstance, f),
    tokenFeeScheduleUpdate: (f = msg.getTokenFeeScheduleUpdate()) && token_fee_schedule_update_pb.TokenFeeScheduleUpdateTransactionBody.toObject(includeInstance, f),
    tokenPause: (f = msg.getTokenPause()) && token_pause_pb.TokenPauseTransactionBody.toObject(includeInstance, f),
    tokenUnpause: (f = msg.getTokenUnpause()) && token_unpause_pb.TokenUnpauseTransactionBody.toObject(includeInstance, f),
    scheduledelete: (f = msg.getScheduledelete()) && schedule_delete_pb.ScheduleDeleteTransactionBody.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.SchedulableTransactionBody}
 */
proto.proto.SchedulableTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.SchedulableTransactionBody;
  return proto.proto.SchedulableTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.SchedulableTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.SchedulableTransactionBody}
 */
proto.proto.SchedulableTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTransactionfee(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemo(value);
      break;
    case 3:
      var value = new contract_call_pb.ContractCallTransactionBody;
      reader.readMessage(value,contract_call_pb.ContractCallTransactionBody.deserializeBinaryFromReader);
      msg.setContractcall(value);
      break;
    case 4:
      var value = new contract_create_pb.ContractCreateTransactionBody;
      reader.readMessage(value,contract_create_pb.ContractCreateTransactionBody.deserializeBinaryFromReader);
      msg.setContractcreateinstance(value);
      break;
    case 5:
      var value = new contract_update_pb.ContractUpdateTransactionBody;
      reader.readMessage(value,contract_update_pb.ContractUpdateTransactionBody.deserializeBinaryFromReader);
      msg.setContractupdateinstance(value);
      break;
    case 6:
      var value = new contract_delete_pb.ContractDeleteTransactionBody;
      reader.readMessage(value,contract_delete_pb.ContractDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setContractdeleteinstance(value);
      break;
    case 37:
      var value = new crypto_adjust_allowance_pb.CryptoAdjustAllowanceTransactionBody;
      reader.readMessage(value,crypto_adjust_allowance_pb.CryptoAdjustAllowanceTransactionBody.deserializeBinaryFromReader);
      msg.setCryptoadjustallowance(value);
      break;
    case 38:
      var value = new crypto_approve_allowance_pb.CryptoApproveAllowanceTransactionBody;
      reader.readMessage(value,crypto_approve_allowance_pb.CryptoApproveAllowanceTransactionBody.deserializeBinaryFromReader);
      msg.setCryptoapproveallowance(value);
      break;
    case 40:
      var value = new crypto_delete_allowance_pb.CryptoDeleteAllowanceTransactionBody;
      reader.readMessage(value,crypto_delete_allowance_pb.CryptoDeleteAllowanceTransactionBody.deserializeBinaryFromReader);
      msg.setCryptodeleteallowance(value);
      break;
    case 7:
      var value = new crypto_create_pb.CryptoCreateTransactionBody;
      reader.readMessage(value,crypto_create_pb.CryptoCreateTransactionBody.deserializeBinaryFromReader);
      msg.setCryptocreateaccount(value);
      break;
    case 8:
      var value = new crypto_delete_pb.CryptoDeleteTransactionBody;
      reader.readMessage(value,crypto_delete_pb.CryptoDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setCryptodelete(value);
      break;
    case 9:
      var value = new crypto_transfer_pb.CryptoTransferTransactionBody;
      reader.readMessage(value,crypto_transfer_pb.CryptoTransferTransactionBody.deserializeBinaryFromReader);
      msg.setCryptotransfer(value);
      break;
    case 10:
      var value = new crypto_update_pb.CryptoUpdateTransactionBody;
      reader.readMessage(value,crypto_update_pb.CryptoUpdateTransactionBody.deserializeBinaryFromReader);
      msg.setCryptoupdateaccount(value);
      break;
    case 11:
      var value = new file_append_pb.FileAppendTransactionBody;
      reader.readMessage(value,file_append_pb.FileAppendTransactionBody.deserializeBinaryFromReader);
      msg.setFileappend(value);
      break;
    case 12:
      var value = new file_create_pb.FileCreateTransactionBody;
      reader.readMessage(value,file_create_pb.FileCreateTransactionBody.deserializeBinaryFromReader);
      msg.setFilecreate(value);
      break;
    case 13:
      var value = new file_delete_pb.FileDeleteTransactionBody;
      reader.readMessage(value,file_delete_pb.FileDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setFiledelete(value);
      break;
    case 14:
      var value = new file_update_pb.FileUpdateTransactionBody;
      reader.readMessage(value,file_update_pb.FileUpdateTransactionBody.deserializeBinaryFromReader);
      msg.setFileupdate(value);
      break;
    case 15:
      var value = new system_delete_pb.SystemDeleteTransactionBody;
      reader.readMessage(value,system_delete_pb.SystemDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setSystemdelete(value);
      break;
    case 16:
      var value = new system_undelete_pb.SystemUndeleteTransactionBody;
      reader.readMessage(value,system_undelete_pb.SystemUndeleteTransactionBody.deserializeBinaryFromReader);
      msg.setSystemundelete(value);
      break;
    case 17:
      var value = new freeze_pb.FreezeTransactionBody;
      reader.readMessage(value,freeze_pb.FreezeTransactionBody.deserializeBinaryFromReader);
      msg.setFreeze(value);
      break;
    case 18:
      var value = new consensus_create_topic_pb.ConsensusCreateTopicTransactionBody;
      reader.readMessage(value,consensus_create_topic_pb.ConsensusCreateTopicTransactionBody.deserializeBinaryFromReader);
      msg.setConsensuscreatetopic(value);
      break;
    case 19:
      var value = new consensus_update_topic_pb.ConsensusUpdateTopicTransactionBody;
      reader.readMessage(value,consensus_update_topic_pb.ConsensusUpdateTopicTransactionBody.deserializeBinaryFromReader);
      msg.setConsensusupdatetopic(value);
      break;
    case 20:
      var value = new consensus_delete_topic_pb.ConsensusDeleteTopicTransactionBody;
      reader.readMessage(value,consensus_delete_topic_pb.ConsensusDeleteTopicTransactionBody.deserializeBinaryFromReader);
      msg.setConsensusdeletetopic(value);
      break;
    case 21:
      var value = new consensus_submit_message_pb.ConsensusSubmitMessageTransactionBody;
      reader.readMessage(value,consensus_submit_message_pb.ConsensusSubmitMessageTransactionBody.deserializeBinaryFromReader);
      msg.setConsensussubmitmessage(value);
      break;
    case 22:
      var value = new token_create_pb.TokenCreateTransactionBody;
      reader.readMessage(value,token_create_pb.TokenCreateTransactionBody.deserializeBinaryFromReader);
      msg.setTokencreation(value);
      break;
    case 23:
      var value = new token_freeze_account_pb.TokenFreezeAccountTransactionBody;
      reader.readMessage(value,token_freeze_account_pb.TokenFreezeAccountTransactionBody.deserializeBinaryFromReader);
      msg.setTokenfreeze(value);
      break;
    case 24:
      var value = new token_unfreeze_account_pb.TokenUnfreezeAccountTransactionBody;
      reader.readMessage(value,token_unfreeze_account_pb.TokenUnfreezeAccountTransactionBody.deserializeBinaryFromReader);
      msg.setTokenunfreeze(value);
      break;
    case 25:
      var value = new token_grant_kyc_pb.TokenGrantKycTransactionBody;
      reader.readMessage(value,token_grant_kyc_pb.TokenGrantKycTransactionBody.deserializeBinaryFromReader);
      msg.setTokengrantkyc(value);
      break;
    case 26:
      var value = new token_revoke_kyc_pb.TokenRevokeKycTransactionBody;
      reader.readMessage(value,token_revoke_kyc_pb.TokenRevokeKycTransactionBody.deserializeBinaryFromReader);
      msg.setTokenrevokekyc(value);
      break;
    case 27:
      var value = new token_delete_pb.TokenDeleteTransactionBody;
      reader.readMessage(value,token_delete_pb.TokenDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setTokendeletion(value);
      break;
    case 28:
      var value = new token_update_pb.TokenUpdateTransactionBody;
      reader.readMessage(value,token_update_pb.TokenUpdateTransactionBody.deserializeBinaryFromReader);
      msg.setTokenupdate(value);
      break;
    case 29:
      var value = new token_mint_pb.TokenMintTransactionBody;
      reader.readMessage(value,token_mint_pb.TokenMintTransactionBody.deserializeBinaryFromReader);
      msg.setTokenmint(value);
      break;
    case 30:
      var value = new token_burn_pb.TokenBurnTransactionBody;
      reader.readMessage(value,token_burn_pb.TokenBurnTransactionBody.deserializeBinaryFromReader);
      msg.setTokenburn(value);
      break;
    case 31:
      var value = new token_wipe_account_pb.TokenWipeAccountTransactionBody;
      reader.readMessage(value,token_wipe_account_pb.TokenWipeAccountTransactionBody.deserializeBinaryFromReader);
      msg.setTokenwipe(value);
      break;
    case 32:
      var value = new token_associate_pb.TokenAssociateTransactionBody;
      reader.readMessage(value,token_associate_pb.TokenAssociateTransactionBody.deserializeBinaryFromReader);
      msg.setTokenassociate(value);
      break;
    case 33:
      var value = new token_dissociate_pb.TokenDissociateTransactionBody;
      reader.readMessage(value,token_dissociate_pb.TokenDissociateTransactionBody.deserializeBinaryFromReader);
      msg.setTokendissociate(value);
      break;
    case 39:
      var value = new token_fee_schedule_update_pb.TokenFeeScheduleUpdateTransactionBody;
      reader.readMessage(value,token_fee_schedule_update_pb.TokenFeeScheduleUpdateTransactionBody.deserializeBinaryFromReader);
      msg.setTokenFeeScheduleUpdate(value);
      break;
    case 35:
      var value = new token_pause_pb.TokenPauseTransactionBody;
      reader.readMessage(value,token_pause_pb.TokenPauseTransactionBody.deserializeBinaryFromReader);
      msg.setTokenPause(value);
      break;
    case 36:
      var value = new token_unpause_pb.TokenUnpauseTransactionBody;
      reader.readMessage(value,token_unpause_pb.TokenUnpauseTransactionBody.deserializeBinaryFromReader);
      msg.setTokenUnpause(value);
      break;
    case 34:
      var value = new schedule_delete_pb.ScheduleDeleteTransactionBody;
      reader.readMessage(value,schedule_delete_pb.ScheduleDeleteTransactionBody.deserializeBinaryFromReader);
      msg.setScheduledelete(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.SchedulableTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.SchedulableTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.SchedulableTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SchedulableTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionfee();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMemo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getContractcall();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      contract_call_pb.ContractCallTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getContractcreateinstance();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      contract_create_pb.ContractCreateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getContractupdateinstance();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      contract_update_pb.ContractUpdateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getContractdeleteinstance();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      contract_delete_pb.ContractDeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptoadjustallowance();
  if (f != null) {
    writer.writeMessage(
      37,
      f,
      crypto_adjust_allowance_pb.CryptoAdjustAllowanceTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptoapproveallowance();
  if (f != null) {
    writer.writeMessage(
      38,
      f,
      crypto_approve_allowance_pb.CryptoApproveAllowanceTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptodeleteallowance();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      crypto_delete_allowance_pb.CryptoDeleteAllowanceTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptocreateaccount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      crypto_create_pb.CryptoCreateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptodelete();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      crypto_delete_pb.CryptoDeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptotransfer();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      crypto_transfer_pb.CryptoTransferTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getCryptoupdateaccount();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      crypto_update_pb.CryptoUpdateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getFileappend();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      file_append_pb.FileAppendTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getFilecreate();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      file_create_pb.FileCreateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getFiledelete();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      file_delete_pb.FileDeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getFileupdate();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      file_update_pb.FileUpdateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getSystemdelete();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      system_delete_pb.SystemDeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getSystemundelete();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      system_undelete_pb.SystemUndeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getFreeze();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      freeze_pb.FreezeTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getConsensuscreatetopic();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      consensus_create_topic_pb.ConsensusCreateTopicTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getConsensusupdatetopic();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      consensus_update_topic_pb.ConsensusUpdateTopicTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getConsensusdeletetopic();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      consensus_delete_topic_pb.ConsensusDeleteTopicTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getConsensussubmitmessage();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      consensus_submit_message_pb.ConsensusSubmitMessageTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokencreation();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      token_create_pb.TokenCreateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenfreeze();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      token_freeze_account_pb.TokenFreezeAccountTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenunfreeze();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      token_unfreeze_account_pb.TokenUnfreezeAccountTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokengrantkyc();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      token_grant_kyc_pb.TokenGrantKycTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenrevokekyc();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      token_revoke_kyc_pb.TokenRevokeKycTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokendeletion();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      token_delete_pb.TokenDeleteTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenupdate();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      token_update_pb.TokenUpdateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenmint();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      token_mint_pb.TokenMintTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenburn();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      token_burn_pb.TokenBurnTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenwipe();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      token_wipe_account_pb.TokenWipeAccountTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenassociate();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      token_associate_pb.TokenAssociateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokendissociate();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      token_dissociate_pb.TokenDissociateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenFeeScheduleUpdate();
  if (f != null) {
    writer.writeMessage(
      39,
      f,
      token_fee_schedule_update_pb.TokenFeeScheduleUpdateTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenPause();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      token_pause_pb.TokenPauseTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getTokenUnpause();
  if (f != null) {
    writer.writeMessage(
      36,
      f,
      token_unpause_pb.TokenUnpauseTransactionBody.serializeBinaryToWriter
    );
  }
  f = message.getScheduledelete();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      schedule_delete_pb.ScheduleDeleteTransactionBody.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 transactionFee = 1;
 * @return {number}
 */
proto.proto.SchedulableTransactionBody.prototype.getTransactionfee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.proto.SchedulableTransactionBody.prototype.setTransactionfee = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string memo = 2;
 * @return {string}
 */
proto.proto.SchedulableTransactionBody.prototype.getMemo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proto.SchedulableTransactionBody.prototype.setMemo = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ContractCallTransactionBody contractCall = 3;
 * @return {?proto.proto.ContractCallTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getContractcall = function() {
  return /** @type{?proto.proto.ContractCallTransactionBody} */ (
    jspb.Message.getWrapperField(this, contract_call_pb.ContractCallTransactionBody, 3));
};


/** @param {?proto.proto.ContractCallTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setContractcall = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearContractcall = function() {
  this.setContractcall(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasContractcall = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ContractCreateTransactionBody contractCreateInstance = 4;
 * @return {?proto.proto.ContractCreateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getContractcreateinstance = function() {
  return /** @type{?proto.proto.ContractCreateTransactionBody} */ (
    jspb.Message.getWrapperField(this, contract_create_pb.ContractCreateTransactionBody, 4));
};


/** @param {?proto.proto.ContractCreateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setContractcreateinstance = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearContractcreateinstance = function() {
  this.setContractcreateinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasContractcreateinstance = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ContractUpdateTransactionBody contractUpdateInstance = 5;
 * @return {?proto.proto.ContractUpdateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getContractupdateinstance = function() {
  return /** @type{?proto.proto.ContractUpdateTransactionBody} */ (
    jspb.Message.getWrapperField(this, contract_update_pb.ContractUpdateTransactionBody, 5));
};


/** @param {?proto.proto.ContractUpdateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setContractupdateinstance = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearContractupdateinstance = function() {
  this.setContractupdateinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasContractupdateinstance = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ContractDeleteTransactionBody contractDeleteInstance = 6;
 * @return {?proto.proto.ContractDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getContractdeleteinstance = function() {
  return /** @type{?proto.proto.ContractDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, contract_delete_pb.ContractDeleteTransactionBody, 6));
};


/** @param {?proto.proto.ContractDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setContractdeleteinstance = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearContractdeleteinstance = function() {
  this.setContractdeleteinstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasContractdeleteinstance = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CryptoAdjustAllowanceTransactionBody cryptoAdjustAllowance = 37;
 * @return {?proto.proto.CryptoAdjustAllowanceTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptoadjustallowance = function() {
  return /** @type{?proto.proto.CryptoAdjustAllowanceTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_adjust_allowance_pb.CryptoAdjustAllowanceTransactionBody, 37));
};


/** @param {?proto.proto.CryptoAdjustAllowanceTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptoadjustallowance = function(value) {
  jspb.Message.setOneofWrapperField(this, 37, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptoadjustallowance = function() {
  this.setCryptoadjustallowance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptoadjustallowance = function() {
  return jspb.Message.getField(this, 37) != null;
};


/**
 * optional CryptoApproveAllowanceTransactionBody cryptoApproveAllowance = 38;
 * @return {?proto.proto.CryptoApproveAllowanceTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptoapproveallowance = function() {
  return /** @type{?proto.proto.CryptoApproveAllowanceTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_approve_allowance_pb.CryptoApproveAllowanceTransactionBody, 38));
};


/** @param {?proto.proto.CryptoApproveAllowanceTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptoapproveallowance = function(value) {
  jspb.Message.setOneofWrapperField(this, 38, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptoapproveallowance = function() {
  this.setCryptoapproveallowance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptoapproveallowance = function() {
  return jspb.Message.getField(this, 38) != null;
};


/**
 * optional CryptoDeleteAllowanceTransactionBody cryptoDeleteAllowance = 40;
 * @return {?proto.proto.CryptoDeleteAllowanceTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptodeleteallowance = function() {
  return /** @type{?proto.proto.CryptoDeleteAllowanceTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_delete_allowance_pb.CryptoDeleteAllowanceTransactionBody, 40));
};


/** @param {?proto.proto.CryptoDeleteAllowanceTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptodeleteallowance = function(value) {
  jspb.Message.setOneofWrapperField(this, 40, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptodeleteallowance = function() {
  this.setCryptodeleteallowance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptodeleteallowance = function() {
  return jspb.Message.getField(this, 40) != null;
};


/**
 * optional CryptoCreateTransactionBody cryptoCreateAccount = 7;
 * @return {?proto.proto.CryptoCreateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptocreateaccount = function() {
  return /** @type{?proto.proto.CryptoCreateTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_create_pb.CryptoCreateTransactionBody, 7));
};


/** @param {?proto.proto.CryptoCreateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptocreateaccount = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptocreateaccount = function() {
  this.setCryptocreateaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptocreateaccount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CryptoDeleteTransactionBody cryptoDelete = 8;
 * @return {?proto.proto.CryptoDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptodelete = function() {
  return /** @type{?proto.proto.CryptoDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_delete_pb.CryptoDeleteTransactionBody, 8));
};


/** @param {?proto.proto.CryptoDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptodelete = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptodelete = function() {
  this.setCryptodelete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptodelete = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional CryptoTransferTransactionBody cryptoTransfer = 9;
 * @return {?proto.proto.CryptoTransferTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptotransfer = function() {
  return /** @type{?proto.proto.CryptoTransferTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_transfer_pb.CryptoTransferTransactionBody, 9));
};


/** @param {?proto.proto.CryptoTransferTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptotransfer = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptotransfer = function() {
  this.setCryptotransfer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptotransfer = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional CryptoUpdateTransactionBody cryptoUpdateAccount = 10;
 * @return {?proto.proto.CryptoUpdateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getCryptoupdateaccount = function() {
  return /** @type{?proto.proto.CryptoUpdateTransactionBody} */ (
    jspb.Message.getWrapperField(this, crypto_update_pb.CryptoUpdateTransactionBody, 10));
};


/** @param {?proto.proto.CryptoUpdateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setCryptoupdateaccount = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearCryptoupdateaccount = function() {
  this.setCryptoupdateaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasCryptoupdateaccount = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional FileAppendTransactionBody fileAppend = 11;
 * @return {?proto.proto.FileAppendTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getFileappend = function() {
  return /** @type{?proto.proto.FileAppendTransactionBody} */ (
    jspb.Message.getWrapperField(this, file_append_pb.FileAppendTransactionBody, 11));
};


/** @param {?proto.proto.FileAppendTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setFileappend = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearFileappend = function() {
  this.setFileappend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasFileappend = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional FileCreateTransactionBody fileCreate = 12;
 * @return {?proto.proto.FileCreateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getFilecreate = function() {
  return /** @type{?proto.proto.FileCreateTransactionBody} */ (
    jspb.Message.getWrapperField(this, file_create_pb.FileCreateTransactionBody, 12));
};


/** @param {?proto.proto.FileCreateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setFilecreate = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearFilecreate = function() {
  this.setFilecreate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasFilecreate = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional FileDeleteTransactionBody fileDelete = 13;
 * @return {?proto.proto.FileDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getFiledelete = function() {
  return /** @type{?proto.proto.FileDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, file_delete_pb.FileDeleteTransactionBody, 13));
};


/** @param {?proto.proto.FileDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setFiledelete = function(value) {
  jspb.Message.setOneofWrapperField(this, 13, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearFiledelete = function() {
  this.setFiledelete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasFiledelete = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional FileUpdateTransactionBody fileUpdate = 14;
 * @return {?proto.proto.FileUpdateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getFileupdate = function() {
  return /** @type{?proto.proto.FileUpdateTransactionBody} */ (
    jspb.Message.getWrapperField(this, file_update_pb.FileUpdateTransactionBody, 14));
};


/** @param {?proto.proto.FileUpdateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setFileupdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 14, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearFileupdate = function() {
  this.setFileupdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasFileupdate = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional SystemDeleteTransactionBody systemDelete = 15;
 * @return {?proto.proto.SystemDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getSystemdelete = function() {
  return /** @type{?proto.proto.SystemDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, system_delete_pb.SystemDeleteTransactionBody, 15));
};


/** @param {?proto.proto.SystemDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setSystemdelete = function(value) {
  jspb.Message.setOneofWrapperField(this, 15, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearSystemdelete = function() {
  this.setSystemdelete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasSystemdelete = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional SystemUndeleteTransactionBody systemUndelete = 16;
 * @return {?proto.proto.SystemUndeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getSystemundelete = function() {
  return /** @type{?proto.proto.SystemUndeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, system_undelete_pb.SystemUndeleteTransactionBody, 16));
};


/** @param {?proto.proto.SystemUndeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setSystemundelete = function(value) {
  jspb.Message.setOneofWrapperField(this, 16, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearSystemundelete = function() {
  this.setSystemundelete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasSystemundelete = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional FreezeTransactionBody freeze = 17;
 * @return {?proto.proto.FreezeTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getFreeze = function() {
  return /** @type{?proto.proto.FreezeTransactionBody} */ (
    jspb.Message.getWrapperField(this, freeze_pb.FreezeTransactionBody, 17));
};


/** @param {?proto.proto.FreezeTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setFreeze = function(value) {
  jspb.Message.setOneofWrapperField(this, 17, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearFreeze = function() {
  this.setFreeze(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasFreeze = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional ConsensusCreateTopicTransactionBody consensusCreateTopic = 18;
 * @return {?proto.proto.ConsensusCreateTopicTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getConsensuscreatetopic = function() {
  return /** @type{?proto.proto.ConsensusCreateTopicTransactionBody} */ (
    jspb.Message.getWrapperField(this, consensus_create_topic_pb.ConsensusCreateTopicTransactionBody, 18));
};


/** @param {?proto.proto.ConsensusCreateTopicTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setConsensuscreatetopic = function(value) {
  jspb.Message.setOneofWrapperField(this, 18, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearConsensuscreatetopic = function() {
  this.setConsensuscreatetopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasConsensuscreatetopic = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional ConsensusUpdateTopicTransactionBody consensusUpdateTopic = 19;
 * @return {?proto.proto.ConsensusUpdateTopicTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getConsensusupdatetopic = function() {
  return /** @type{?proto.proto.ConsensusUpdateTopicTransactionBody} */ (
    jspb.Message.getWrapperField(this, consensus_update_topic_pb.ConsensusUpdateTopicTransactionBody, 19));
};


/** @param {?proto.proto.ConsensusUpdateTopicTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setConsensusupdatetopic = function(value) {
  jspb.Message.setOneofWrapperField(this, 19, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearConsensusupdatetopic = function() {
  this.setConsensusupdatetopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasConsensusupdatetopic = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional ConsensusDeleteTopicTransactionBody consensusDeleteTopic = 20;
 * @return {?proto.proto.ConsensusDeleteTopicTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getConsensusdeletetopic = function() {
  return /** @type{?proto.proto.ConsensusDeleteTopicTransactionBody} */ (
    jspb.Message.getWrapperField(this, consensus_delete_topic_pb.ConsensusDeleteTopicTransactionBody, 20));
};


/** @param {?proto.proto.ConsensusDeleteTopicTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setConsensusdeletetopic = function(value) {
  jspb.Message.setOneofWrapperField(this, 20, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearConsensusdeletetopic = function() {
  this.setConsensusdeletetopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasConsensusdeletetopic = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional ConsensusSubmitMessageTransactionBody consensusSubmitMessage = 21;
 * @return {?proto.proto.ConsensusSubmitMessageTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getConsensussubmitmessage = function() {
  return /** @type{?proto.proto.ConsensusSubmitMessageTransactionBody} */ (
    jspb.Message.getWrapperField(this, consensus_submit_message_pb.ConsensusSubmitMessageTransactionBody, 21));
};


/** @param {?proto.proto.ConsensusSubmitMessageTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setConsensussubmitmessage = function(value) {
  jspb.Message.setOneofWrapperField(this, 21, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearConsensussubmitmessage = function() {
  this.setConsensussubmitmessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasConsensussubmitmessage = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional TokenCreateTransactionBody tokenCreation = 22;
 * @return {?proto.proto.TokenCreateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokencreation = function() {
  return /** @type{?proto.proto.TokenCreateTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_create_pb.TokenCreateTransactionBody, 22));
};


/** @param {?proto.proto.TokenCreateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokencreation = function(value) {
  jspb.Message.setOneofWrapperField(this, 22, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokencreation = function() {
  this.setTokencreation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokencreation = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional TokenFreezeAccountTransactionBody tokenFreeze = 23;
 * @return {?proto.proto.TokenFreezeAccountTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenfreeze = function() {
  return /** @type{?proto.proto.TokenFreezeAccountTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_freeze_account_pb.TokenFreezeAccountTransactionBody, 23));
};


/** @param {?proto.proto.TokenFreezeAccountTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenfreeze = function(value) {
  jspb.Message.setOneofWrapperField(this, 23, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenfreeze = function() {
  this.setTokenfreeze(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenfreeze = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional TokenUnfreezeAccountTransactionBody tokenUnfreeze = 24;
 * @return {?proto.proto.TokenUnfreezeAccountTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenunfreeze = function() {
  return /** @type{?proto.proto.TokenUnfreezeAccountTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_unfreeze_account_pb.TokenUnfreezeAccountTransactionBody, 24));
};


/** @param {?proto.proto.TokenUnfreezeAccountTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenunfreeze = function(value) {
  jspb.Message.setOneofWrapperField(this, 24, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenunfreeze = function() {
  this.setTokenunfreeze(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenunfreeze = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional TokenGrantKycTransactionBody tokenGrantKyc = 25;
 * @return {?proto.proto.TokenGrantKycTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokengrantkyc = function() {
  return /** @type{?proto.proto.TokenGrantKycTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_grant_kyc_pb.TokenGrantKycTransactionBody, 25));
};


/** @param {?proto.proto.TokenGrantKycTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokengrantkyc = function(value) {
  jspb.Message.setOneofWrapperField(this, 25, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokengrantkyc = function() {
  this.setTokengrantkyc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokengrantkyc = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional TokenRevokeKycTransactionBody tokenRevokeKyc = 26;
 * @return {?proto.proto.TokenRevokeKycTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenrevokekyc = function() {
  return /** @type{?proto.proto.TokenRevokeKycTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_revoke_kyc_pb.TokenRevokeKycTransactionBody, 26));
};


/** @param {?proto.proto.TokenRevokeKycTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenrevokekyc = function(value) {
  jspb.Message.setOneofWrapperField(this, 26, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenrevokekyc = function() {
  this.setTokenrevokekyc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenrevokekyc = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional TokenDeleteTransactionBody tokenDeletion = 27;
 * @return {?proto.proto.TokenDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokendeletion = function() {
  return /** @type{?proto.proto.TokenDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_delete_pb.TokenDeleteTransactionBody, 27));
};


/** @param {?proto.proto.TokenDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokendeletion = function(value) {
  jspb.Message.setOneofWrapperField(this, 27, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokendeletion = function() {
  this.setTokendeletion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokendeletion = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional TokenUpdateTransactionBody tokenUpdate = 28;
 * @return {?proto.proto.TokenUpdateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenupdate = function() {
  return /** @type{?proto.proto.TokenUpdateTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_update_pb.TokenUpdateTransactionBody, 28));
};


/** @param {?proto.proto.TokenUpdateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenupdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 28, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenupdate = function() {
  this.setTokenupdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenupdate = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional TokenMintTransactionBody tokenMint = 29;
 * @return {?proto.proto.TokenMintTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenmint = function() {
  return /** @type{?proto.proto.TokenMintTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_mint_pb.TokenMintTransactionBody, 29));
};


/** @param {?proto.proto.TokenMintTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenmint = function(value) {
  jspb.Message.setOneofWrapperField(this, 29, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenmint = function() {
  this.setTokenmint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenmint = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional TokenBurnTransactionBody tokenBurn = 30;
 * @return {?proto.proto.TokenBurnTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenburn = function() {
  return /** @type{?proto.proto.TokenBurnTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_burn_pb.TokenBurnTransactionBody, 30));
};


/** @param {?proto.proto.TokenBurnTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenburn = function(value) {
  jspb.Message.setOneofWrapperField(this, 30, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenburn = function() {
  this.setTokenburn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenburn = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional TokenWipeAccountTransactionBody tokenWipe = 31;
 * @return {?proto.proto.TokenWipeAccountTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenwipe = function() {
  return /** @type{?proto.proto.TokenWipeAccountTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_wipe_account_pb.TokenWipeAccountTransactionBody, 31));
};


/** @param {?proto.proto.TokenWipeAccountTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenwipe = function(value) {
  jspb.Message.setOneofWrapperField(this, 31, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenwipe = function() {
  this.setTokenwipe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenwipe = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional TokenAssociateTransactionBody tokenAssociate = 32;
 * @return {?proto.proto.TokenAssociateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenassociate = function() {
  return /** @type{?proto.proto.TokenAssociateTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_associate_pb.TokenAssociateTransactionBody, 32));
};


/** @param {?proto.proto.TokenAssociateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenassociate = function(value) {
  jspb.Message.setOneofWrapperField(this, 32, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenassociate = function() {
  this.setTokenassociate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenassociate = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional TokenDissociateTransactionBody tokenDissociate = 33;
 * @return {?proto.proto.TokenDissociateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokendissociate = function() {
  return /** @type{?proto.proto.TokenDissociateTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_dissociate_pb.TokenDissociateTransactionBody, 33));
};


/** @param {?proto.proto.TokenDissociateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokendissociate = function(value) {
  jspb.Message.setOneofWrapperField(this, 33, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokendissociate = function() {
  this.setTokendissociate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokendissociate = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional TokenFeeScheduleUpdateTransactionBody token_fee_schedule_update = 39;
 * @return {?proto.proto.TokenFeeScheduleUpdateTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenFeeScheduleUpdate = function() {
  return /** @type{?proto.proto.TokenFeeScheduleUpdateTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_fee_schedule_update_pb.TokenFeeScheduleUpdateTransactionBody, 39));
};


/** @param {?proto.proto.TokenFeeScheduleUpdateTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenFeeScheduleUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 39, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenFeeScheduleUpdate = function() {
  this.setTokenFeeScheduleUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenFeeScheduleUpdate = function() {
  return jspb.Message.getField(this, 39) != null;
};


/**
 * optional TokenPauseTransactionBody token_pause = 35;
 * @return {?proto.proto.TokenPauseTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenPause = function() {
  return /** @type{?proto.proto.TokenPauseTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_pause_pb.TokenPauseTransactionBody, 35));
};


/** @param {?proto.proto.TokenPauseTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenPause = function(value) {
  jspb.Message.setOneofWrapperField(this, 35, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenPause = function() {
  this.setTokenPause(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenPause = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional TokenUnpauseTransactionBody token_unpause = 36;
 * @return {?proto.proto.TokenUnpauseTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getTokenUnpause = function() {
  return /** @type{?proto.proto.TokenUnpauseTransactionBody} */ (
    jspb.Message.getWrapperField(this, token_unpause_pb.TokenUnpauseTransactionBody, 36));
};


/** @param {?proto.proto.TokenUnpauseTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setTokenUnpause = function(value) {
  jspb.Message.setOneofWrapperField(this, 36, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearTokenUnpause = function() {
  this.setTokenUnpause(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasTokenUnpause = function() {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional ScheduleDeleteTransactionBody scheduleDelete = 34;
 * @return {?proto.proto.ScheduleDeleteTransactionBody}
 */
proto.proto.SchedulableTransactionBody.prototype.getScheduledelete = function() {
  return /** @type{?proto.proto.ScheduleDeleteTransactionBody} */ (
    jspb.Message.getWrapperField(this, schedule_delete_pb.ScheduleDeleteTransactionBody, 34));
};


/** @param {?proto.proto.ScheduleDeleteTransactionBody|undefined} value */
proto.proto.SchedulableTransactionBody.prototype.setScheduledelete = function(value) {
  jspb.Message.setOneofWrapperField(this, 34, proto.proto.SchedulableTransactionBody.oneofGroups_[0], value);
};


proto.proto.SchedulableTransactionBody.prototype.clearScheduledelete = function() {
  this.setScheduledelete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SchedulableTransactionBody.prototype.hasScheduledelete = function() {
  return jspb.Message.getField(this, 34) != null;
};


goog.object.extend(exports, proto.proto);
