/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var basic_types_pb = require('./basic_types_pb.js');
var timestamp_pb = require('./timestamp_pb.js');
goog.exportSymbol('proto.proto.SystemDeleteTransactionBody', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.SystemDeleteTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.proto.SystemDeleteTransactionBody.oneofGroups_);
};
goog.inherits(proto.proto.SystemDeleteTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.SystemDeleteTransactionBody.displayName = 'proto.proto.SystemDeleteTransactionBody';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.proto.SystemDeleteTransactionBody.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.proto.SystemDeleteTransactionBody.IdCase = {
  ID_NOT_SET: 0,
  FILEID: 1,
  CONTRACTID: 2
};

/**
 * @return {proto.proto.SystemDeleteTransactionBody.IdCase}
 */
proto.proto.SystemDeleteTransactionBody.prototype.getIdCase = function() {
  return /** @type {proto.proto.SystemDeleteTransactionBody.IdCase} */(jspb.Message.computeOneofCase(this, proto.proto.SystemDeleteTransactionBody.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.SystemDeleteTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.SystemDeleteTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.SystemDeleteTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SystemDeleteTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileid: (f = msg.getFileid()) && basic_types_pb.FileID.toObject(includeInstance, f),
    contractid: (f = msg.getContractid()) && basic_types_pb.ContractID.toObject(includeInstance, f),
    expirationtime: (f = msg.getExpirationtime()) && timestamp_pb.TimestampSeconds.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.SystemDeleteTransactionBody}
 */
proto.proto.SystemDeleteTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.SystemDeleteTransactionBody;
  return proto.proto.SystemDeleteTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.SystemDeleteTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.SystemDeleteTransactionBody}
 */
proto.proto.SystemDeleteTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.FileID;
      reader.readMessage(value,basic_types_pb.FileID.deserializeBinaryFromReader);
      msg.setFileid(value);
      break;
    case 2:
      var value = new basic_types_pb.ContractID;
      reader.readMessage(value,basic_types_pb.ContractID.deserializeBinaryFromReader);
      msg.setContractid(value);
      break;
    case 3:
      var value = new timestamp_pb.TimestampSeconds;
      reader.readMessage(value,timestamp_pb.TimestampSeconds.deserializeBinaryFromReader);
      msg.setExpirationtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.SystemDeleteTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.SystemDeleteTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.SystemDeleteTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SystemDeleteTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.FileID.serializeBinaryToWriter
    );
  }
  f = message.getContractid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      basic_types_pb.ContractID.serializeBinaryToWriter
    );
  }
  f = message.getExpirationtime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      timestamp_pb.TimestampSeconds.serializeBinaryToWriter
    );
  }
};


/**
 * optional FileID fileID = 1;
 * @return {?proto.proto.FileID}
 */
proto.proto.SystemDeleteTransactionBody.prototype.getFileid = function() {
  return /** @type{?proto.proto.FileID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.FileID, 1));
};


/** @param {?proto.proto.FileID|undefined} value */
proto.proto.SystemDeleteTransactionBody.prototype.setFileid = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.proto.SystemDeleteTransactionBody.oneofGroups_[0], value);
};


proto.proto.SystemDeleteTransactionBody.prototype.clearFileid = function() {
  this.setFileid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SystemDeleteTransactionBody.prototype.hasFileid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ContractID contractID = 2;
 * @return {?proto.proto.ContractID}
 */
proto.proto.SystemDeleteTransactionBody.prototype.getContractid = function() {
  return /** @type{?proto.proto.ContractID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.ContractID, 2));
};


/** @param {?proto.proto.ContractID|undefined} value */
proto.proto.SystemDeleteTransactionBody.prototype.setContractid = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.proto.SystemDeleteTransactionBody.oneofGroups_[0], value);
};


proto.proto.SystemDeleteTransactionBody.prototype.clearContractid = function() {
  this.setContractid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SystemDeleteTransactionBody.prototype.hasContractid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TimestampSeconds expirationTime = 3;
 * @return {?proto.proto.TimestampSeconds}
 */
proto.proto.SystemDeleteTransactionBody.prototype.getExpirationtime = function() {
  return /** @type{?proto.proto.TimestampSeconds} */ (
    jspb.Message.getWrapperField(this, timestamp_pb.TimestampSeconds, 3));
};


/** @param {?proto.proto.TimestampSeconds|undefined} value */
proto.proto.SystemDeleteTransactionBody.prototype.setExpirationtime = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.proto.SystemDeleteTransactionBody.prototype.clearExpirationtime = function() {
  this.setExpirationtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.SystemDeleteTransactionBody.prototype.hasExpirationtime = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.proto);
