/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var basic_types_pb = require('./basic_types_pb.js');
var custom_fees_pb = require('./custom_fees_pb.js');
goog.exportSymbol('proto.proto.TokenFeeScheduleUpdateTransactionBody', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.TokenFeeScheduleUpdateTransactionBody.repeatedFields_, null);
};
goog.inherits(proto.proto.TokenFeeScheduleUpdateTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.TokenFeeScheduleUpdateTransactionBody.displayName = 'proto.proto.TokenFeeScheduleUpdateTransactionBody';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.TokenFeeScheduleUpdateTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.TokenFeeScheduleUpdateTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenId: (f = msg.getTokenId()) && basic_types_pb.TokenID.toObject(includeInstance, f),
    customFeesList: jspb.Message.toObjectList(msg.getCustomFeesList(),
    custom_fees_pb.CustomFee.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.TokenFeeScheduleUpdateTransactionBody}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.TokenFeeScheduleUpdateTransactionBody;
  return proto.proto.TokenFeeScheduleUpdateTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.TokenFeeScheduleUpdateTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.TokenFeeScheduleUpdateTransactionBody}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.TokenID;
      reader.readMessage(value,basic_types_pb.TokenID.deserializeBinaryFromReader);
      msg.setTokenId(value);
      break;
    case 2:
      var value = new custom_fees_pb.CustomFee;
      reader.readMessage(value,custom_fees_pb.CustomFee.deserializeBinaryFromReader);
      msg.addCustomFees(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.TokenFeeScheduleUpdateTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.TokenFeeScheduleUpdateTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.TokenID.serializeBinaryToWriter
    );
  }
  f = message.getCustomFeesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      custom_fees_pb.CustomFee.serializeBinaryToWriter
    );
  }
};


/**
 * optional TokenID token_id = 1;
 * @return {?proto.proto.TokenID}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.getTokenId = function() {
  return /** @type{?proto.proto.TokenID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.TokenID, 1));
};


/** @param {?proto.proto.TokenID|undefined} value */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.setTokenId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.clearTokenId = function() {
  this.setTokenId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.hasTokenId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CustomFee custom_fees = 2;
 * @return {!Array.<!proto.proto.CustomFee>}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.getCustomFeesList = function() {
  return /** @type{!Array.<!proto.proto.CustomFee>} */ (
    jspb.Message.getRepeatedWrapperField(this, custom_fees_pb.CustomFee, 2));
};


/** @param {!Array.<!proto.proto.CustomFee>} value */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.setCustomFeesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.CustomFee=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.CustomFee}
 */
proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.addCustomFees = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.CustomFee, opt_index);
};


proto.proto.TokenFeeScheduleUpdateTransactionBody.prototype.clearCustomFeesList = function() {
  this.setCustomFeesList([]);
};


goog.object.extend(exports, proto.proto);
