/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var transaction_record_pb = require('./transaction_record_pb.js');
var basic_types_pb = require('./basic_types_pb.js');
var query_header_pb = require('./query_header_pb.js');
var response_header_pb = require('./response_header_pb.js');
goog.exportSymbol('proto.proto.TransactionGetRecordQuery', null, global);
goog.exportSymbol('proto.proto.TransactionGetRecordResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.TransactionGetRecordQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.TransactionGetRecordQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.TransactionGetRecordQuery.displayName = 'proto.proto.TransactionGetRecordQuery';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.TransactionGetRecordQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.TransactionGetRecordQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.TransactionGetRecordQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TransactionGetRecordQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && query_header_pb.QueryHeader.toObject(includeInstance, f),
    transactionid: (f = msg.getTransactionid()) && basic_types_pb.TransactionID.toObject(includeInstance, f),
    includeduplicates: jspb.Message.getFieldWithDefault(msg, 3, false),
    includeChildRecords: jspb.Message.getFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.TransactionGetRecordQuery}
 */
proto.proto.TransactionGetRecordQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.TransactionGetRecordQuery;
  return proto.proto.TransactionGetRecordQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.TransactionGetRecordQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.TransactionGetRecordQuery}
 */
proto.proto.TransactionGetRecordQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new query_header_pb.QueryHeader;
      reader.readMessage(value,query_header_pb.QueryHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new basic_types_pb.TransactionID;
      reader.readMessage(value,basic_types_pb.TransactionID.deserializeBinaryFromReader);
      msg.setTransactionid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeduplicates(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeChildRecords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.TransactionGetRecordQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.TransactionGetRecordQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.TransactionGetRecordQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TransactionGetRecordQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      query_header_pb.QueryHeader.serializeBinaryToWriter
    );
  }
  f = message.getTransactionid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      basic_types_pb.TransactionID.serializeBinaryToWriter
    );
  }
  f = message.getIncludeduplicates();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getIncludeChildRecords();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional QueryHeader header = 1;
 * @return {?proto.proto.QueryHeader}
 */
proto.proto.TransactionGetRecordQuery.prototype.getHeader = function() {
  return /** @type{?proto.proto.QueryHeader} */ (
    jspb.Message.getWrapperField(this, query_header_pb.QueryHeader, 1));
};


/** @param {?proto.proto.QueryHeader|undefined} value */
proto.proto.TransactionGetRecordQuery.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.TransactionGetRecordQuery.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TransactionGetRecordQuery.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionID transactionID = 2;
 * @return {?proto.proto.TransactionID}
 */
proto.proto.TransactionGetRecordQuery.prototype.getTransactionid = function() {
  return /** @type{?proto.proto.TransactionID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.TransactionID, 2));
};


/** @param {?proto.proto.TransactionID|undefined} value */
proto.proto.TransactionGetRecordQuery.prototype.setTransactionid = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.proto.TransactionGetRecordQuery.prototype.clearTransactionid = function() {
  this.setTransactionid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TransactionGetRecordQuery.prototype.hasTransactionid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool includeDuplicates = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.proto.TransactionGetRecordQuery.prototype.getIncludeduplicates = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.proto.TransactionGetRecordQuery.prototype.setIncludeduplicates = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool include_child_records = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.proto.TransactionGetRecordQuery.prototype.getIncludeChildRecords = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.proto.TransactionGetRecordQuery.prototype.setIncludeChildRecords = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.TransactionGetRecordResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.TransactionGetRecordResponse.repeatedFields_, null);
};
goog.inherits(proto.proto.TransactionGetRecordResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.TransactionGetRecordResponse.displayName = 'proto.proto.TransactionGetRecordResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.TransactionGetRecordResponse.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.TransactionGetRecordResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.TransactionGetRecordResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.TransactionGetRecordResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TransactionGetRecordResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && response_header_pb.ResponseHeader.toObject(includeInstance, f),
    transactionrecord: (f = msg.getTransactionrecord()) && transaction_record_pb.TransactionRecord.toObject(includeInstance, f),
    duplicatetransactionrecordsList: jspb.Message.toObjectList(msg.getDuplicatetransactionrecordsList(),
    transaction_record_pb.TransactionRecord.toObject, includeInstance),
    childTransactionRecordsList: jspb.Message.toObjectList(msg.getChildTransactionRecordsList(),
    transaction_record_pb.TransactionRecord.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.TransactionGetRecordResponse}
 */
proto.proto.TransactionGetRecordResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.TransactionGetRecordResponse;
  return proto.proto.TransactionGetRecordResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.TransactionGetRecordResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.TransactionGetRecordResponse}
 */
proto.proto.TransactionGetRecordResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new response_header_pb.ResponseHeader;
      reader.readMessage(value,response_header_pb.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 3:
      var value = new transaction_record_pb.TransactionRecord;
      reader.readMessage(value,transaction_record_pb.TransactionRecord.deserializeBinaryFromReader);
      msg.setTransactionrecord(value);
      break;
    case 4:
      var value = new transaction_record_pb.TransactionRecord;
      reader.readMessage(value,transaction_record_pb.TransactionRecord.deserializeBinaryFromReader);
      msg.addDuplicatetransactionrecords(value);
      break;
    case 5:
      var value = new transaction_record_pb.TransactionRecord;
      reader.readMessage(value,transaction_record_pb.TransactionRecord.deserializeBinaryFromReader);
      msg.addChildTransactionRecords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.TransactionGetRecordResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.TransactionGetRecordResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.TransactionGetRecordResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.TransactionGetRecordResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      response_header_pb.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getTransactionrecord();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      transaction_record_pb.TransactionRecord.serializeBinaryToWriter
    );
  }
  f = message.getDuplicatetransactionrecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      transaction_record_pb.TransactionRecord.serializeBinaryToWriter
    );
  }
  f = message.getChildTransactionRecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      transaction_record_pb.TransactionRecord.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseHeader header = 1;
 * @return {?proto.proto.ResponseHeader}
 */
proto.proto.TransactionGetRecordResponse.prototype.getHeader = function() {
  return /** @type{?proto.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, response_header_pb.ResponseHeader, 1));
};


/** @param {?proto.proto.ResponseHeader|undefined} value */
proto.proto.TransactionGetRecordResponse.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.TransactionGetRecordResponse.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TransactionGetRecordResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionRecord transactionRecord = 3;
 * @return {?proto.proto.TransactionRecord}
 */
proto.proto.TransactionGetRecordResponse.prototype.getTransactionrecord = function() {
  return /** @type{?proto.proto.TransactionRecord} */ (
    jspb.Message.getWrapperField(this, transaction_record_pb.TransactionRecord, 3));
};


/** @param {?proto.proto.TransactionRecord|undefined} value */
proto.proto.TransactionGetRecordResponse.prototype.setTransactionrecord = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.proto.TransactionGetRecordResponse.prototype.clearTransactionrecord = function() {
  this.setTransactionrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.TransactionGetRecordResponse.prototype.hasTransactionrecord = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated TransactionRecord duplicateTransactionRecords = 4;
 * @return {!Array.<!proto.proto.TransactionRecord>}
 */
proto.proto.TransactionGetRecordResponse.prototype.getDuplicatetransactionrecordsList = function() {
  return /** @type{!Array.<!proto.proto.TransactionRecord>} */ (
    jspb.Message.getRepeatedWrapperField(this, transaction_record_pb.TransactionRecord, 4));
};


/** @param {!Array.<!proto.proto.TransactionRecord>} value */
proto.proto.TransactionGetRecordResponse.prototype.setDuplicatetransactionrecordsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.proto.TransactionRecord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.TransactionRecord}
 */
proto.proto.TransactionGetRecordResponse.prototype.addDuplicatetransactionrecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.proto.TransactionRecord, opt_index);
};


proto.proto.TransactionGetRecordResponse.prototype.clearDuplicatetransactionrecordsList = function() {
  this.setDuplicatetransactionrecordsList([]);
};


/**
 * repeated TransactionRecord child_transaction_records = 5;
 * @return {!Array.<!proto.proto.TransactionRecord>}
 */
proto.proto.TransactionGetRecordResponse.prototype.getChildTransactionRecordsList = function() {
  return /** @type{!Array.<!proto.proto.TransactionRecord>} */ (
    jspb.Message.getRepeatedWrapperField(this, transaction_record_pb.TransactionRecord, 5));
};


/** @param {!Array.<!proto.proto.TransactionRecord>} value */
proto.proto.TransactionGetRecordResponse.prototype.setChildTransactionRecordsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.proto.TransactionRecord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.TransactionRecord}
 */
proto.proto.TransactionGetRecordResponse.prototype.addChildTransactionRecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.proto.TransactionRecord, opt_index);
};


proto.proto.TransactionGetRecordResponse.prototype.clearChildTransactionRecordsList = function() {
  this.setChildTransactionRecordsList([]);
};


goog.object.extend(exports, proto.proto);
