/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var basic_types_pb = require('./basic_types_pb.js');
var duration_pb = require('./duration_pb.js');
var timestamp_pb = require('./timestamp_pb.js');
goog.exportSymbol('proto.proto.ConsensusUpdateTopicTransactionBody', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ConsensusUpdateTopicTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.ConsensusUpdateTopicTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.ConsensusUpdateTopicTransactionBody.displayName = 'proto.proto.ConsensusUpdateTopicTransactionBody';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ConsensusUpdateTopicTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ConsensusUpdateTopicTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ConsensusUpdateTopicTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    topicid: (f = msg.getTopicid()) && basic_types_pb.TopicID.toObject(includeInstance, f),
    memo: (f = msg.getMemo()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    expirationtime: (f = msg.getExpirationtime()) && timestamp_pb.Timestamp.toObject(includeInstance, f),
    adminkey: (f = msg.getAdminkey()) && basic_types_pb.Key.toObject(includeInstance, f),
    submitkey: (f = msg.getSubmitkey()) && basic_types_pb.Key.toObject(includeInstance, f),
    autorenewperiod: (f = msg.getAutorenewperiod()) && duration_pb.Duration.toObject(includeInstance, f),
    autorenewaccount: (f = msg.getAutorenewaccount()) && basic_types_pb.AccountID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ConsensusUpdateTopicTransactionBody}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ConsensusUpdateTopicTransactionBody;
  return proto.proto.ConsensusUpdateTopicTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ConsensusUpdateTopicTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ConsensusUpdateTopicTransactionBody}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new basic_types_pb.TopicID;
      reader.readMessage(value,basic_types_pb.TopicID.deserializeBinaryFromReader);
      msg.setTopicid(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setMemo(value);
      break;
    case 4:
      var value = new timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirationtime(value);
      break;
    case 6:
      var value = new basic_types_pb.Key;
      reader.readMessage(value,basic_types_pb.Key.deserializeBinaryFromReader);
      msg.setAdminkey(value);
      break;
    case 7:
      var value = new basic_types_pb.Key;
      reader.readMessage(value,basic_types_pb.Key.deserializeBinaryFromReader);
      msg.setSubmitkey(value);
      break;
    case 8:
      var value = new duration_pb.Duration;
      reader.readMessage(value,duration_pb.Duration.deserializeBinaryFromReader);
      msg.setAutorenewperiod(value);
      break;
    case 9:
      var value = new basic_types_pb.AccountID;
      reader.readMessage(value,basic_types_pb.AccountID.deserializeBinaryFromReader);
      msg.setAutorenewaccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ConsensusUpdateTopicTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ConsensusUpdateTopicTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ConsensusUpdateTopicTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopicid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      basic_types_pb.TopicID.serializeBinaryToWriter
    );
  }
  f = message.getMemo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getExpirationtime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAdminkey();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      basic_types_pb.Key.serializeBinaryToWriter
    );
  }
  f = message.getSubmitkey();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      basic_types_pb.Key.serializeBinaryToWriter
    );
  }
  f = message.getAutorenewperiod();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getAutorenewaccount();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      basic_types_pb.AccountID.serializeBinaryToWriter
    );
  }
};


/**
 * optional TopicID topicID = 1;
 * @return {?proto.proto.TopicID}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getTopicid = function() {
  return /** @type{?proto.proto.TopicID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.TopicID, 1));
};


/** @param {?proto.proto.TopicID|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setTopicid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearTopicid = function() {
  this.setTopicid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasTopicid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue memo = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getMemo = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setMemo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearMemo = function() {
  this.setMemo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasMemo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Timestamp expirationTime = 4;
 * @return {?proto.proto.Timestamp}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getExpirationtime = function() {
  return /** @type{?proto.proto.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_pb.Timestamp, 4));
};


/** @param {?proto.proto.Timestamp|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setExpirationtime = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearExpirationtime = function() {
  this.setExpirationtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasExpirationtime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Key adminKey = 6;
 * @return {?proto.proto.Key}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getAdminkey = function() {
  return /** @type{?proto.proto.Key} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.Key, 6));
};


/** @param {?proto.proto.Key|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setAdminkey = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearAdminkey = function() {
  this.setAdminkey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasAdminkey = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Key submitKey = 7;
 * @return {?proto.proto.Key}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getSubmitkey = function() {
  return /** @type{?proto.proto.Key} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.Key, 7));
};


/** @param {?proto.proto.Key|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setSubmitkey = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearSubmitkey = function() {
  this.setSubmitkey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasSubmitkey = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Duration autoRenewPeriod = 8;
 * @return {?proto.proto.Duration}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getAutorenewperiod = function() {
  return /** @type{?proto.proto.Duration} */ (
    jspb.Message.getWrapperField(this, duration_pb.Duration, 8));
};


/** @param {?proto.proto.Duration|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setAutorenewperiod = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearAutorenewperiod = function() {
  this.setAutorenewperiod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasAutorenewperiod = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional AccountID autoRenewAccount = 9;
 * @return {?proto.proto.AccountID}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.getAutorenewaccount = function() {
  return /** @type{?proto.proto.AccountID} */ (
    jspb.Message.getWrapperField(this, basic_types_pb.AccountID, 9));
};


/** @param {?proto.proto.AccountID|undefined} value */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.setAutorenewaccount = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.proto.ConsensusUpdateTopicTransactionBody.prototype.clearAutorenewaccount = function() {
  this.setAutorenewaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ConsensusUpdateTopicTransactionBody.prototype.hasAutorenewaccount = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto.proto);
